### ISSUE TITLE
How would one set a sound?

### ISSUE THREAD

**Issue by RudraPSinha** [Pandawan/deno_notify#2]
There is confusion about how would one set a custom sound. Would one have to keep a sound file in the root directory and mention the name of the file in the `notify({OPTIONS})`. 

The sample code does not produce any sound on Windows when triggered.

**Comment by PandawanFr** [comment]
Oops, sorry the example I've put is for macOS. I'll make sure to update the documentation to reflect the available options

I don't have a windows desktop to test this with, but I believe that for windows, the available sounds are `Default`, `IM`, `Mail`, `Reminder`, and `SMS` (from [winrt_notification](https://github.com/allenbenz/winrt-notification/blob/master/src/lib.rs#L69) and the [Microsoft docs](https://docs.microsoft.com/en-us/uwp/schemas/tiles/toastschema/element-audio#attributes-and-elements)).

For macOS, the available notification sounds are `Basso`, `Blow`, `Bottle`, `Frog`, `Funk`, `Glass`, `Hero`, `Morse`, `Ping`, `Pop`, `Purr`, `Sosumi`, `Submarine`, and `Tink` (from [mac-notification-sys](https://github.com/h4llow3En/mac-notification-sys/blob/master/src/lib.rs#L159) which shows the path where the sound files can be retrieved).

I don't believe either library has direct support for custom sounds though I believe macOS will allow for any sound found in the specific sound directories.

And Unix does not support custom sounds as the moment.
