### ISSUE TITLE
Error Uncaught TypeError

### ISSUE THREAD

**Issue by DavidLibeau** [Pandawan/deno_notify#3]
Hi, I have this error while trying running the example code.
```
error: Uncaught (in promise) TypeError: invalid promise id: expected type `rusty_v8::data::Integer`, got `rusty_v8::data::Value`
  const response = core.dispatch(opId, encode(data))!;
                        ^
    at opSync (https://deno.land/x/deno_notify@0.4.5/ts/plugin.ts:49:25)
    at notify (https://deno.land/x/deno_notify@0.4.5/ts/mod.ts:90:5)
    at …app.ts:19:1
```
Mac OS 11.2

**Comment by DavidLibeau** [comment]
I'm thinking maybe this problem come from my local env, but I don't know how to resolve it, if rust can be updated in some way or not…

**Comment by Pandawan** [comment]
This seems to be an [issue with Deno 1.9](https://github.com/denoland/deno/issues/10192); [they're overhauling the plugin system](https://github.com/denoland/deno/pull/10427) and plugins seem to be temporarily broken as a result. I'll look into finding a fix while we wait for 1.10, but we might just have to wait and see.

**Comment by DavidLibeau** [comment]
1.9 is broken for everyone. Closing this issue as it is not code related. Thanks

**Comment by Pandawan** [comment]
fyi, I’m working on adding 1.10 support. However, I’ve hit another issue with the plugin system which I’ve reported on GH, so we’ve gotta wait for a patch release.
