### ISSUE TITLE
does not work at all on windows

### ISSUE THREAD

**Issue by arnimlost** [Pandawan/deno_notify#4]
maybe it's just me, or this package/plugin does not work on Windows. I tried both examples in the README, screenshots are below. (It just results in an [`os error 127`](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-), I guess something is wrong with the [.dll](https://github.com/Pandawan/deno_notify/releases/download/0.4.5/deno_notify.dll))

### manual import
![manual import](https://user-images.githubusercontent.com/74423013/118155607-b000f680-b418-11eb-9c8a-d1ce425fe621.png)

### using prepared.ts
![using prepared.ts](https://user-images.githubusercontent.com/74423013/118155633-b68f6e00-b418-11eb-892b-58bf6d9d34cf.png)

**Comment by Pandawan** [comment]
Yup, this is [normal right now](https://github.com/Pandawan/deno_notify/issues/3). I’m still working on upgrading the library to Deno 1.10 but unfortunately there is a breaking issue that is still waiting for a fix. Until a patch release comes out you can revert to Deno 1.8 or wait. Sorry for the inconvenience.

**Comment by arnimlost** [comment]
No problem, I just wanted to try it out, didn't even think about incompability.

Btw, what do you use this for? The only usecase I can imagine is sending error messages if you have a process running in the background, since (afaik), there is nothing like Electron (only [alephjs](https://alephjs.org/), which is more like react) for Deno.

PS: I just saw your minecraft function pre-processor and it seems to fix the whole only-one-expression-per-line thing that kept me from starting a serious datapack project, so I'll definitely try it out :)
