### ISSUE TITLE
Suggestion: Add to Nest.land

### ISSUE THREAD

**Issue by Redstoneguy129** [Pandawan/deno_notify#8]

**Comment by Pandawan** [comment]
Not sure I want to go through the trouble of maintaining two sources/registries. I feel like the benefits of having a package on the blockchain are very minimal when we have GitHub & deno.land/x. If I'm missing something, I'm open for discussion.

**Comment by Redstoneguy129** [comment]
A simple github actions workflow
[https://github.com/michael-spengler/mac-address/tree/master/.github/workflows](https://github.com/michael-spengler/mac-address/tree/master/.github/workflows)
